tinyMCE.addI18n('pt.GoogleMapsDialog',{
	title: 'Editor para Mapas da Google',
	general: 'Geral',
	advanced: 'Avançado',
	map:"Mapa", 
	location: "Localização", 
	coordinates: "Coordenadas", 
	coordinates_latitude: "Latitude",
	coordinates_longitude: "Longitude",
	address: "Endereço", 
	defaultaddress: "Cidade, País", 
	search: "Procurar",
	map_size: "Tamanho do Mapa", 
	pixel: "Pixel", 
	width:"Largura", 
	height:"Altura", 
	map_options: "Opções do Mapa", 
	zoom_level: "Nível de Zoom",
	map_style: "Estilo do Mapa", 
	map_style_normal: "Mapa Normal", 
	map_style_satellite: "Vista de Satélite", 
	map_style_hybrid: "Mapa Híbrido", 
	map_style_physical: "Mapa do Terreno", 
	map_controls: "Controles do Mapa", 
	map_controls_zoom_position: "Navegação", 
	map_controls_zoom_position_default: "Por omissão", 
	map_controls_zoom_position_small: "Pequeno", 
	map_controls_zoom_position_android: "Android", 
	map_controls_zoom_position_zoom_pan: "Zoom e Pan", 
	map_controls_zoom_position_none: "Nenhum", 
	map_controls_zoom_position_default_title: "O controlo de navegação por omissão, que irá variar de acordo com o tamanho do mapa e outros factores. Poderá ser modificado em futuras actualizações da API", 
	map_controls_zoom_position_small_title: "Apenas um pequeno controlo de zoom", 
	map_controls_zoom_position_android_title: "Um pequeno controlo de zoom semelhante ao utilizado na aplicação nativa de mapas do Android", 
	map_controls_zoom_position_zoom_pan_title: "Um controlo maior, com uma barra de zoom deslizante e um controlo direcional", 
	map_controls_zoom_position_none_title: "Sem controlos", 
	map_controls_map_type: "Tipo de mapa",
	map_controls_map_type_default: 'Por omissão',
	map_controls_map_type_horizontal_bar: 'Menu horizontal',
	map_controls_map_type_dropdown_menu: 'Menu pendente',
	map_controls_map_type_none: 'Nenhum',
	map_controls_map_type_default_title: 'Utiliza o controlo de tipo de mapa por omissão, que irá variar de acordo com o tamanho do mapa e outros factores. Poderá ser modificado em futuras actualizações da API',
	map_controls_map_type_horizontal_bar_title: 'Menu horizontal mais comum',
	map_controls_map_type_dropdown_menu_title: 'Menu vertical para economizar espaço',
	map_controls_map_type_none_title: 'Sem selector de tipo de mapa',
	map_controls_scale: 'Escala',
	map_controls_scale_standard: 'Por omissão',
	map_controls_scale_none: 'Nenhum',
	map_controls_scale_standard_title: 'O controlo de escala por omissão',
	map_controls_scale_none_title: 'Sem controlo de escala',
	invalid_coordinates: "As coordenadas são inválidas!",
	error_ocorred: "Erro",
	no_rows_selected: "Deve seleccionar as linhas a serem eliminadas",
	info_window: "Janela de informação",
	info_window_title: "Título",
	info_window_content: "Conteúdo",
	map_icon: "Ícone do Mapa",
	map_icon_url: "URL da Imagem do Ícone",
	map_icon_image_title: "Endereço da imagem de primeiro plano a utilizar como ícone",
	map_icon_shadow_url: "URL da Imagem de Sombra",
	map_icon_shadow_image_title: "Endereço da imagem a utilizar como sombra do ícone",
	drag_icon: "Arraste para actualizar as coordenadas",
	search_unsuccessful: "O Geocode devolveu um problema"
});
