tinyMCE.addI18n('en.GoogleMapsDialog',{
	title: 'Google Maps Editor',
	general: 'General',
	advanced: 'Advanced',
	location: "Location", 
	coordinates: "Coordinates", 
	coordinates_latitude: "Latitude",
	coordinates_longitude: "Longitude",
	address: "Address", 
	defaultaddress: "City, Country", 
	search: "Search",
	map_size: "Map Size", 
	pixel: "Pixel", 
	width:"Width", 
	height:"Height", 
	map_options: "Map Options", 
	zoom_level: "Zoom Level",
	map_style: "Map Style", 
	map_style_normal: "Normal Map", 
	map_style_satellite: "Satellite Map", 
	map_style_hybrid: "Hybrid Map", 
	map_style_physical: "Physical Map", 
	map_controls: "Map Controls", 
	map_controls_zoom_position: "Navigation", 
	map_controls_zoom_position_default: "Default", 
	map_controls_zoom_position_small: "Small", 
	map_controls_zoom_position_android: "Android", 
	map_controls_zoom_position_zoom_pan: "Zoom and Pan", 
	map_controls_zoom_position_none: "None", 
	map_controls_zoom_position_default_title: "The default navigation control. The control which DEFAULT maps to will vary according to map size and other factors. It may change in future versions of the API", 
	map_controls_zoom_position_small_title: "The small, zoom only control", 
	map_controls_zoom_position_android_title: "The small zoom control similar to the one used by the native Maps application on Android", 
	map_controls_zoom_position_zoom_pan_title: "The larger control, with the zoom slider and pan directional pad", 
	map_controls_zoom_position_none_title: "Without controls", 
	map_controls_map_type: "Map type control",
	map_controls_map_type_default: 'Default',
	map_controls_map_type_horizontal_bar: 'Horizontal bar',
	map_controls_map_type_dropdown_menu: 'Dropdown menu',
	map_controls_map_type_none: 'None',
	map_controls_map_type_default_title: 'Uses the default map type control. The control which DEFAULT maps to will vary according to window size and other factors. It may change in future versions of the API',
	map_controls_map_type_horizontal_bar_title: 'The standard horizontal radio buttons bar',
	map_controls_map_type_dropdown_menu_title: 'A dropdown menu for the screen realestate conscious',
	map_controls_map_type_none_title: 'Without map type control',
	map_controls_scale: 'Scale',
	map_controls_scale_standard: 'Standard',
	map_controls_scale_none: 'None',
	map_controls_scale_standard_title: 'The standard scale control',
	map_controls_scale_none_title: 'Without scale control',
	invalid_coordinates: "Your coordinates are invalid!",
	error_ocorred: "Error",
	info_window: "Information Window",
	info_window_title: "Title",
	info_window_content: "Content",
	map_icon: "Map Icon",
	map_icon_url: "Icon Image URL",
	map_icon_image_title: "The foreground image URL of the icon",
	map_icon_shadow_url: "Icon Shadow Image URL",
	map_icon_shadow_image_title: "The shadow image URL of the icon",
	drag_icon: "Drag me to update the coordinates",
	search_unsuccessful: "Ocorreu um problema"
});
